[package]
name = "sovra-mpc-dkls23-silence"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
sovra-eth = { workspace = true }
sovra-network = { workspace = true }
sovra-mpc = { workspace = true }
sovra-types = { workspace = true }
sovra-state = { workspace = true }
alloy-primitives = { workspace = true, features = ["k256"] }
k256 = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
rand = { workspace = true }
derivation-path = { workspace = true }
sl-dkls23 = { workspace = true, features = ["test-support"] }
sl-mpc-mate = { workspace = true, features = ["simple-relay"] }
ed25519-dalek = { workspace = true }
futures-util = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
