[package]
name = "sovra-policy"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
alloy-primitives = { workspace = true, features = ["serde"] }
serde = { workspace = true }
sovra-network = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
toml = { workspace = true }
