[package]
name = "sovra-api"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
config = "0.15"
serde = { version = "1", features = ["derive"] }
sovra-eth = { workspace = true }
sovra-observability = { workspace = true }
sovra-mpc = { workspace = true }
sovra-mpc-dkls23-silence = { workspace = true }
sovra-state = { workspace = true }
sovra-types = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
alloy-primitives = { workspace = true, features = ["serde"] }
serde_json = { workspace = true }
axum = { workspace = true }
alloy-provider = { workspace = true }
utoipa = { workspace = true }
utoipa-swagger-ui = { workspace = true, features = ["axum"] }
tracing = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
alloy-consensus = { workspace = true }
tower = { workspace = true, features = ["util"] }
http-body-util = { workspace = true }
tempfile = { workspace = true }
